// Board: STM32F103C8T6
// IDE: STM32CubeIDE
// Rest of the config code is Autogenerated in IDE

#include "stm32f1xx_hal.h"
#include "stdio.h"
#include "string.h"

float Read_Temp(void);        // Function prototype

int main(void)
{

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();
  
  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_ADC1_Init();
  MX_USART1_UART_Init();

  /* USER CODE BEGIN 2 */

  char msg[30];

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {

	  float temp = Read_Temp();

	  sprintf(msg, "Temperature : %.2f *C\r\n", temp);
	  HAL_UART_Transmit(&huart1, (uint8_t *)msg, strlen(msg), HAL_MAX_DELAY);

  }
}

  float Read_Temp(void){

		uint32_t value =0;

		HAL_ADC_Start(&hadc1);
		HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
		value = HAL_ADC_GetValue(&hadc1);

		float voltage = (value * 5.0)/4096.0 ;			          	// V=5.0 bcoz sensor is conected to +5v
		float temperature = (voltage - 0.5)*100.0 ;			        // Offset value = 0.5
		return temperature;
	}
